import { GetStaticProps } from "next";
import Head from "next/head";
import Link from "next/link";
import { SinglePost } from "../../components/Post/SinglePost";
import { Tag } from "../../components/Tag/Tag";
import { getAllTags, getPostsTopPage } from "../../lib/notionAPI";

// 4つずつデータを取得↓
export const getStaticProps: GetStaticProps = async () => {
  const fourPosts = await getPostsTopPage(4);
  const allTags = await getAllTags();

  return {
    props: {
      fourPosts,
      allTags,
    },
    // ISRを使用、6時間ごとに画面（HTML）を更新する。
    revalidate: 60 * 60 * 6,
  };
};

export default function Home({ fourPosts, allTags }) {
  // console.log(allPosts);
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          Notion Blog🚀
        </h1>
        {fourPosts.map((post) => (
          <div className="mx-4" key={post.id}>
            <SinglePost
              title={post.title}
              description={post.description}
              date={post.date}
              tags={post.tags}
              slug={post.slug}
              isPagenationPage={false}
            />
          </div>
        ))}
        <Link
          href="/posts/page/1"
          className="mb-6 lg:w-1/2 mx-auto rounded-md px-5 block text-right"
        >
          もっと見ろ
        </Link>
        <Tag tags={allTags} />
      </main>
    </div>
  );
}
